import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service - OmegleNew | Free Stranger Chat',
  description: 'Read the OmegleNew Terms of Service. Rules and conditions for using our free anonymous stranger chat platform — the best Omegle alternative.',
  alternates: { canonical: 'https://omeglenew.com/terms' },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content:
        'By accessing or using OmegleNew, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree, do not use this service.',
    },
    {
      title: '2. Age Requirement — 18+ ONLY',
      content:
        'OmegleNew is strictly for users who are 18 years of age or older. Minors are prohibited under any circumstances. By using OmegleNew, you represent and warrant that you are at least 18 years old. We reserve the right to terminate accounts of suspected minors immediately.',
    },
    {
      title: '3. Prohibited Conduct',
      content:
        'You agree NOT to: (a) harass, bully, or threaten other users; (b) share, solicit, or display explicit, sexual, or nude content; (c) engage in hate speech, discrimination, racism, or bigotry of any kind; (d) solicit personal information from other users; (e) promote or engage in illegal activities including drug use, violence, or self-harm; (f) spam, advertise, or solicit commercial services; (g) impersonate other individuals or entities; (h) use the service for any purpose that violates applicable law.',
    },
    {
      title: '4. User Responsibility',
      content:
        'You are solely responsible for all content you transmit through OmegleNew. OmegleNew is not responsible for the actions, statements, or conduct of other users. Always exercise caution and never share personal financial information, passwords, or sensitive personal details with strangers.',
    },
    {
      title: '5. Privacy',
      content:
        'OmegleNew does not require registration or personal information to use. Chat messages are not stored on our servers. However, your IP address and approximate geolocation may be logged for security and legal compliance purposes.',
    },
    {
      title: '6. Enforcement',
      content:
        'Violations of these Terms may result in immediate suspension or permanent ban without prior notice. A three-strikes system applies for minor violations: Warning → 24-hour ban → Permanent ban. Severe violations (nudity, minors, illegal activity) result in immediate permanent bans and may be reported to law enforcement.',
    },
    {
      title: '7. Disclaimer of Warranties',
      content:
        'OmegleNew is provided "as is" without any warranties of any kind. We do not guarantee the accuracy, reliability, or safety of conversations. You use this service at your own risk.',
    },
    {
      title: '8. Limitation of Liability',
      content:
        'OmegleNew and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of this service or exposure to content generated by other users.',
    },
    {
      title: '9. Changes to Terms',
      content:
        'We reserve the right to modify these Terms at any time. Continued use of OmegleNew after changes constitutes acceptance of the new Terms.',
    },
    {
      title: '10. Governing Law',
      content:
        'These Terms shall be governed by applicable laws. Any disputes shall be resolved through binding arbitration.',
    },
  ];

  return (
    <>
      <Header />
      <main className="max-w-3xl mx-auto px-4 py-12">
        <div className="mb-8">
          <Link href="/" className="text-brand-600 hover:text-brand-700 text-sm font-medium flex items-center gap-1 mb-4">
            ← Back to OmegleNew
          </Link>
          <h1 className="text-4xl font-extrabold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: January 2026</p>
        </div>

        <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-8">
          <p className="text-red-700 font-semibold text-sm">
            ⚠ OmegleNew is strictly 18+ only. Minors are prohibited from using this platform.
          </p>
        </div>

        <div className="prose prose-gray max-w-none">
          <p className="text-gray-600 leading-relaxed mb-8">
            Welcome to OmegleNew. These Terms of Service govern your use of our anonymous text
            chat platform. Please read them carefully before using our service.
          </p>

          <div className="space-y-8">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="text-xl font-bold text-gray-900 mb-3">{section.title}</h2>
                <p className="text-gray-600 leading-relaxed">{section.content}</p>
              </section>
            ))}
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <p className="text-gray-500 text-sm">
            Questions about our Terms?{' '}
            <Link href="/guidelines" className="text-brand-600 hover:underline">
              Read our Community Guidelines
            </Link>{' '}
            or{' '}
            <Link href="/privacy" className="text-brand-600 hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
